### PR TITLE
Allow real requests except for webpay

### PR DESCRIPTION
**Pull request by necojackarc**
WebMock stubs out all requests when the settings are default.
Using default settings, WebMock stubs out requests to even localhost.

It seems not to be proper to stub out all requests except for WebPay.

## Diff
* Add `WebMock.allow_net_connect!` to `lib/webpay/mock/webmock_wrapper.rb`

### Reference
* https://github.com/bblimke/webmock#real-requests-to-network-can-be-allowed-or-disabled

## Samples
Some sample cases are below:

#### Request to 127.0.0.1

```ruby
Net::HTTP.get(URI.parse("http://127.0.0.1"))
```

```
Failure/Error: Net::HTTP.get(URI.parse("http://127.0.0.1"))

WebMock::NetConnectNotAllowedError:
  Real HTTP connections are disabled. Unregistered request: GET http://127.0.0.1/ with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'127.0.0.1', 'User-Agent'=>'Ruby'}

  You can stub this request with the following snippet:

  stub_request(:get, "http://127.0.0.1/").
    with(:headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'127.0.0.1', 'User-Agent'=>'Ruby'}).
    to_return(:status => 200, :body => "", :headers => {})

  ============================================================
```

#### Request to localhost

```ruby
Net::HTTP.get(URI.parse("http://localhost"))
```

```
Failure/Error: Net::HTTP.get(URI.parse("http://localhost"))

WebMock::NetConnectNotAllowedError:
  Real HTTP connections are disabled. Unregistered request: GET http://localhost/ with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'localhost', 'User-Agent'=>'Ruby'}

  You can stub this request with the following snippet:

  stub_request(:get, "http://localhost/").
    with(:headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'localhost', 'User-Agent'=>'Ruby'}).
    to_return(:status => 200, :body => "", :headers => {})

  ============================================================
```

#### Request to 127.0.0.1

```ruby
Net::HTTP.get(URI.parse("http://127.0.0.1"))
```

```
Failure/Error: Net::HTTP.get(URI.parse("http://127.0.0.1"))

Errno::ECONNREFUSED:
  Connection refused - connect(2) for "127.0.0.1" port 80
```

#### Request to localhost

```ruby
Net::HTTP.get(URI.parse("http://localhost"))
```

```
Failure/Error: Net::HTTP.get(URI.parse("http://localhost"))

Errno::ECONNREFUSED:
  Connection refused - connect(2) for "localhost" port 80
```

## Specs
I have not added any tests, but no existing tests have been affected by this change.

Thanks.

### CODE REVIEW

**Comment by tomykaira** [comment]
> WebMock stubs out all requests when the settings are default.
> Using default settings, WebMock stubs out requests to even localhost.

This behavior follows our testing policy.

> It seems not to be proper to stub out all requests except for WebPay.

Such behavior is better, but it is not acceptable to globally alter WebMock default for that.
Some users rely on WebMock to find out unexpected HTTP requests.

**Comment by necojackarc** [comment]
@tomykaira 
> Such behavior is better, but it is not acceptable to globally alter WebMock default for that.

I totally agree with you, it is terrible to globally alter WebMock's behaviour :cold_sweat:
I overlooked that this change causes global modification :sweat_drops: 
 
I think, however, this gem is just "WebPay Mock", not "WebMock", you know.
Therefore, users do not need to know the dependency on WebMock of this gem.

> Some users rely on WebMock to find out unexpected HTTP requests.

Viewed from the opposite side, some might rely on real HTTP requests.
Perhaps, issue #6 may be connected to this PR.

Then, I have updated my PR, but It looks like a dirty and ugly solution :astonished: 
What do you think?

#### Samples after adopting this PR
When a user do not use WebMock:
```ruby
require "webpay/mock"
require "net/http"

Net::HTTP.get(URI.parse("http://127.0.0.1"))
=> `initialize': Connection refused - connect(2) for "127.0.0.1" port 80 (Errno::ECONNREFUSED)
```

When a user use WebMock
```ruby
require "webpay/mock"
require "net/http"
require "webmock"

=> `request': Real HTTP connections are disabled. Unregistered request: GET http://127.0.0.1/ with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'127.0.0.1', 'User-Agent'=>'Ruby'} (WebMock::NetConnectNotAllowedError)
```

**Comment by necojackarc** [comment]
@tomykaira 
> Such behavior is better, but it is not acceptable to globally alter WebMock default for that.

I totally agree with you, it is terrible to globally alter WebMock's behaviour :cold_sweat:
I overlooked that this change causes global modification :sweat_drops: 
 
I think, however, this gem is just "WebPay Mock", not "WebMock", you know.
Therefore, users do not need to know the dependency on WebMock of this gem.

> Some users rely on WebMock to find out unexpected HTTP requests.

Viewed from the opposite side, some might rely on real HTTP requests.
Perhaps, issue #6 may be connected to this PR.

Then, I have updated my PR, but It looks like a dirty and ugly solution :astonished: 
What do you think?

#### Samples after adopting this PR
When a user do not use WebMock:
```ruby
require "webpay/mock"
require "net/http"

Net::HTTP.get(URI.parse("http://127.0.0.1"))
=> `initialize': Connection refused - connect(2) for "127.0.0.1" port 80 (Errno::ECONNREFUSED)
```

When a user use WebMock
```ruby
require "webpay/mock"
require "net/http"
require "webmock"

=> `request': Real HTTP connections are disabled. Unregistered request: GET http://127.0.0.1/ with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'127.0.0.1', 'User-Agent'=>'Ruby'} (WebMock::NetConnectNotAllowedError)
```

**Comment by tomykaira** [comment]
It also fails if webmock is loaded after this gem.
Because of compatibility, we cannot merge this request. Thank you for the suggestion.

**Comment by necojackarc** [comment]
@tomykaira 
Okay, I got it, there is a good chance that it breaks compatibility.
However, I feel you misunderstood a little.

> It also fails if webmock is loaded after this gem.

It fails if WebMock is loaded after CALLING `webpay_stub`, not loading the gem.
Thank you for your kind reply.

**Comment by necojackarc** [comment]
@tomykaira 
What do you think about providing `configure` method?
When a user does not call `configure`, nothing is being changed.

Like this:
```ruby
class WebPay
  module Mock
    module Configurable
      Configuration = Struct.new(:allow_other_requests)

      def configure
        config = Configuration.new
        yield config

        if config.allow_other_requests
          WebMock.allow_net_connect!
        else
          WebMock.disable_net_connect!
        end
      end
    end
  end
end
```

```ruby
module WebPay::Mock::WebMockWrapper
  extend  WebPay::Mock::Configurable
  :
  :
end
```

```ruby
describe 'configure' do
  let(:external_uri) { URI.parse("http://127.0.0.1") }

  subject { -> { Net::HTTP.get(external_uri) } }

  context 'calling configure' do
    before do
      WebPay::Mock::WebMockWrapper.configure do |config|
        config.allow_other_requests = allow_other_requests
      end
    end

    after do
      WebPay::Mock::WebMockWrapper.configure do |config|
        config.allow_other_requests = false
      end
    end

    context 'allow other real requests' do
      let(:allow_other_requests) { true }
      it { is_expected.not_to raise_error(WebMock::NetConnectNotAllowedError) }
    end

    context 'not allow other real requests' do
      let(:allow_other_requests) { false }
      it { is_expected.to raise_error(WebMock::NetConnectNotAllowedError) }
    end
  end

  context 'do not configure the mock' do
    it { is_expected.to raise_error(WebMock::NetConnectNotAllowedError) }
  end
end
```

**Comment by yasaichi** [comment]
@tomykaira 
> This behavior follows our testing policy.

What is your "testing policy", or the purpose of this gem?

If it includes supporting developers who request WebPay APIs without [webpay gem](https://rubygems.org/gems/webpay), it may be correct to stub out all HTTP requests.

However, if it is only to support users of webpay gem, it seems incorrect because they probably expect the gem to stub only the API requests.

I think this problem is caused by using not [faraday's stub](https://github.com/lostisland/faraday#using-faraday-for-testing) but webmock to sub the requests.
If you use the former way, you avoid the side effect of the latter way.

What do you think?

**Comment by necojackarc** [comment]
@yasaichi I couldn't agree more :+1:

**Comment by hmsk** [comment]
Thanks for your opinions, guys.

We think:
"In test, all external connections stubbed out. Should be raised when unexpected connection are made."

So we want the developers should stub out if they have other connections to external.

And this project is made as the wrapper of WebMock, Also spin off from our application including request to WebPay and some more.

Sorry for inconvenience about making some troubles, if you're not using WebMock or not stubbing any external connections out as the precondition :cry: 

However we welcome the patch that is backward-compatible.
About the suggestion by @necojackarc, using configure-pattern, let us consider.
https://github.com/webpay/webpay-mock/pull/7#issuecomment-182690480
but just write `allow_net_connect!` in your project is easy way, I think?

Regards.

**Comment by necojackarc** [comment]
@hmsk 
Thank you for your reply. I understood your policy.
Plus, as you said, this is a wrapper of WebMock, so it might be okay.

However, I have a bit of a question.
Based on your policy, you prohibit the developers from using the following kind of tools in testing, don't you?

- [DynamoDBLocal - Running DynamoDB on Your Computer](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.html)

--

> but just write allow_net_connect! in your project is easy way, I think?

Actually, I've already adopted this way to get along with the WebPay Mock :+1:

**Comment by hmsk** [comment]
> Based on your policy, you prohibit the developers from using the following kind of tools in testing, don't you?

yep, I'm feeling sorry about the case like this.
Certainly, our library has the big effect to whole the project what includes. We consider about avoiding.
For example: as the feature, enabling/disabling stub clearly in developer's project.

for now, we can't support nothing more :crying_cat_face: 

Thanks for your understanding.

**Comment by necojackarc** [comment]
I understand. I am grateful for your polite response :smile:

**Pull request closed without merging**
